name: My Sample Invalid Pipeline
description: This is Invalid pipeline description
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
